export enum ECategoryControllerAction {
  GET_CATEGORYS = 'GET_CATEGORYS',
  GET_CATEGORYS_REQUEST = 'GET_CATEGORYS_REQUEST',
  GET_CATEGORYS_SUCCESS = 'GET_CATEGORYS_SUCCESS',
  GET_CATEGORYS_FAILED = 'GET_CATEGORYS_FAILED',

  GET_CATEGORY = 'GET_CATEGORY',
  GET_CATEGORY_REQUEST = 'GET_CATEGORY_REQUEST',
  GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS',
  GET_CATEGORY_FAILED = 'GET_CATEGORY_FAILED',
}
