export enum EVoucherControllerAction {
  GET_VOUCHERS = 'GET_VOUCHERS',
  GET_VOUCHERS_REQUEST = 'GET_VOUCHERS_REQUEST',
  GET_VOUCHERS_SUCCESS = 'GET_VOUCHERS_SUCCESS',
  GET_VOUCHERS_FAILED = 'GET_VOUCHERS_FAILED',

  GET_VOUCHER = 'GET_VOUCHER',
  GET_VOUCHER_REQUEST = 'GET_VOUCHER_REQUEST',
  GET_VOUCHER_SUCCESS = 'GET_VOUCHER_SUCCESS',
  GET_VOUCHER_FAILED = 'GET_VOUCHER_FAILED',
}
