export enum EContactControllerAction {
  POST_CONTACT = 'POST_CONTACT',
  POST_CONTACT_REQUEST = 'POST_CONTACT_REQUEST',
  POST_CONTACT_SUCCESS = 'POST_CONTACT_SUCCESS',
  POST_CONTACT_FAILED = 'POST_CONTACT_FAILED',

  POST_AGENT = 'POST_AGENT',
  POST_AGENT_REQUEST = 'POST_AGENT_REQUEST',
  POST_AGENT_SUCCESS = 'POST_AGENT_SUCCESS',
  POST_AGENT_FAILED = 'POST_AGENT_FAILED',
}
