export enum EBannerControllerAction {
  GET_BANNERS = 'GET_BANNERS',
  GET_BANNERS_REQUEST = 'GET_BANNERS_REQUEST',
  GET_BANNERS_SUCCESS = 'GET_BANNERS_SUCCESS',
  GET_BANNERS_FAILED = 'GET_BANNERS_FAILED',

  GET_BANNER = 'GET_BANNER',
  GET_BANNER_REQUEST = 'GET_BANNER_REQUEST',
  GET_BANNER_SUCCESS = 'GET_BANNER_SUCCESS',
  GET_BANNER_FAILED = 'GET_BANNER_FAILED',
}
