export const dataAppotapayErrorCode = [
  { code: '0', message: 'Thành công' },
  { code: '1', message: 'Các tham số yêu cầu thiếu hoặc không hợp lệ' },
  { code: '2', message: 'Tham số signature không chính xác' },
  { code: '11', message: 'Partner không tồn tại' },
  { code: '13', message: 'Partner đã bị khoá' },
  { code: '14', message: 'API KEY không đúng' },
  { code: '15', message: 'Sẩn phẩm chưa được kích hoạt hoặc đã bị khoá' },
  { code: '21', message: 'Sai OTP' },
  { code: '30', message: 'Mã đơn hàng bị trùng' },
  { code: '32', message: 'Số tiền thanh toán không hợp lệ' },
  { code: '33', message: 'Giao dịch không thành công do khách hàng không thực hiện giao dịch' },
  { code: '34', message: 'Giao dịch đang được xử lý, vui lòng thử lại sau' },
  { code: '35', message: 'Giao dịch đang chờ được xử lý, vui lòng thử lại sau' },
  { code: '36', message: 'Giao dịch không tồn tại' },
  { code: '37', message: 'Giao dịch không xác định' },
  { code: '38', message: 'Người dùng huỷ giao dịch' },
  { code: '40', message: 'Giao dịch đã được hoàn trả' },
  { code: '51', message: 'Mã ngân hàng không tồn tại' },
  { code: '52', message: 'Phương thức thanh toán không hợp lệ' },
  { code: '61', message: 'Giao dịch bị từ chối' },
  { code: '62', message: 'Ngân hàng đang bảo trì' },
  { code: '63', message: 'Thẻ chưa kích hoạt hoặc chưa đăng ký thanh toán online' },
  { code: '64', message: 'Loại thẻ chưa được hỗ trợ' },
  { code: '65', message: 'Thông tin thẻ không đúng' },
  { code: '66', message: 'Thẻ của bạn đang bị hạn chế, vui lòng liên hệ ngân hàng để biết thông tin chi tiết' },
  { code: '67', message: 'Thông tin ngày mở thẻ không đúng' },
  { code: '68', message: 'Thẻ của bạn đã bị khoá' },
  { code: '69', message: 'Thẻ của bạn đã hết hạn' },
  { code: '70', message: 'Bạn đã giao dịch vượt quá giới hạn cho phép trong ngày, vui lòng thử lại sau' },
  { code: '71', message: 'Thông tin tên chủ thẻ không đúng' },
  { code: '72', message: 'Cổng thanh toán không nhận được kết quả trả về từ ngân hàng phát hành thẻ' },
  { code: '73', message: 'Thông tin ngày hết hạn thẻ không đúng' },
  { code: '74', message: 'Thẻ không đủ hạn mức hoặc tài khoản không đủ số dư để thanh toán.' },
  { code: '75', message: 'Số tiền không đủ để thanh toán' },
  { code: '76', message: 'Số thẻ không đúng.' },
  { code: '77', message: 'Quá thời gian thanh toán' },
  { code: '78', message: 'Lỗi từ hệ thống ngân hàng, vui lòng thực hiện lại giao dịch' },
  { code: '79', message: 'Không thể xử lý thẻ của bạn, vui lòng liên hệ nhà cung câp để được hỗ trợ' },
  { code: '80', message: 'Mã CVC/CVV không chính xác' },
  { code: '81', message: 'Thẻ không hỗ trợ 3DS' },
  { code: '82', message: 'Thẻ của bạn đã bị từ chối giao dịch, vui lòng liên hệ để biết thông tin chi tiết' },
  { code: '83', message: 'Giao dịch bị từ chối, vui lòng liên hệ để biết thông tin chi tiết' },
  { code: '84', message: 'Số tiền giao dịch quá giới hạn cho phép, vui lòng liên hệ để được hỗ trợ' },
  { code: '85', message: 'Số lượng thẻ giao dịch quá giới hạn cho phép, vui lòng liên hệ để được hỗ trợ' },
  { code: '91', message: 'Hệ thống đang bận, vui lòng thử lại sau' },
  { code: '89', message: 'Thẻ của bạn bị từ chối (do quốc gia phát hành thẻ ko hợp lệ)' },
  { code: '92', message: 'IP không được phép truy cập' },
  { code: '94', message: 'Hệ thống đang bảo trì' },
  { code: '99', message: 'Lỗi không xác định, vui lòng kiểm tra lại giao dịch sau' },
  { code: '105', message: 'Số tiền hoàn lại không được quá số tiền giao dịch' },
  { code: '106', message: 'Giao dịch không hỗ trợ refund một phần' },
  { code: '110', message: 'Tổng số tiền refund vượt quá số tiền giao dịch' },
  { code: '120', message: 'Tài khoản của người dùng bị đóng băng' },
  { code: '121', message: 'Tài khoản ví của người dùng đã vượt quá giới hạn' },
  { code: '125', message: 'Không thể hoàn tiền cho giao dịch vì đã quá thời hạn hoàn tiền' },
  { code: '126', message: 'Giao dịch hoàn tiền không thành công do vi phạm quy định nhà cung cấp dịch vụ' },
  { code: '127', message: 'Yêu cầu hoàn lại tiền cho giao dịch thanh toán không thành công' },
  { code: '401', message: 'Lỗi xác thực ( do JWT Token không đúng hoặc đã hết hạn)' },
  { code: '500', message: 'Lỗi hệ thống' },
];
