export enum EPaymentControllerAction {
  GET_PAYMENT_HISTORYS = 'GET_PAYMENT_HISTORYS',
  GET_PAYMENT_HISTORYS_REQUEST = 'GET_PAYMENT_HISTORYS_REQUEST',
  GET_PAYMENT_HISTORYS_SUCCESS = 'GET_PAYMENT_HISTORYS_SUCCESS',
  GET_PAYMENT_HISTORYS_FAILED = 'GET_PAYMENT_HISTORYS_FAILED',

  GET_PAYMENT_HISTORY = 'GET_PAYMENT_HISTORY',
  GET_PAYMENT_HISTORY_REQUEST = 'GET_PAYMENT_HISTORY_REQUEST',
  GET_PAYMENT_HISTORY_SUCCESS = 'GET_PAYMENT_HISTORY_SUCCESS',
  GET_PAYMENT_HISTORY_FAILED = 'GET_PAYMENT_HISTORY_FAILED',

  CREATE_PAYMENT = 'CREATE_PAYMENT',
  CREATE_PAYMENT_REQUEST = 'CREATE_PAYMENT_REQUEST',
  CREATE_PAYMENT_SUCCESS = 'CREATE_PAYMENT_SUCCESS',
  CREATE_PAYMENT_FAILED = 'CREATE_PAYMENT_FAILED',

  CREATE_PAYMENT_ORDER = 'CREATE_PAYMENT_ORDER',
  CREATE_PAYMENT_ORDER_REQUEST = 'CREATE_PAYMENT_ORDER_REQUEST',
  CREATE_PAYMENT_ORDER_SUCCESS = 'CREATE_PAYMENT_ORDER_SUCCESS',
  CREATE_PAYMENT_ORDER_FAILED = 'CREATE_PAYMENT_ORDER_FAILED',

  RETURN_PAYMENT = 'RETURN_PAYMENT',
  RETURN_PAYMENT_REQUEST = 'RETURN_PAYMENT_REQUEST',
  RETURN_PAYMENT_SUCCESS = 'RETURN_PAYMENT_SUCCESS',
  RETURN_PAYMENT_FAILED = 'RETURN_PAYMENT_FAILED',
}
