export enum ENewControllerAction {
  GET_NEWS = 'GET_NEWS',
  GET_NEWS_REQUEST = 'GET_NEWS_REQUEST',
  GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS',
  GET_NEWS_FAILED = 'GET_NEWS_FAILED',

  GET_NEW = 'GET_NEW',
  GET_NEW_REQUEST = 'GET_NEW_REQUEST',
  GET_NEW_SUCCESS = 'GET_NEW_SUCCESS',
  GET_NEW_FAILED = 'GET_NEW_FAILED',
}
