export enum EAddressControllerAction {
  GET_ADDRESS = 'GET_ADDRESS',
  GET_ADDRESS_REQUEST = 'GET_ADDRESS_REQUEST',
  GET_ADDRESS_SUCCESS = 'GET_ADDRESS_SUCCESS',
  GET_ADDRESS_FAILED = 'GET_ADDRESS_FAILED',
}
