export enum EPackMealControllerAction {
  GET_PACK_MEALS = 'GET_PACK_MEALS',
  GET_PACK_MEALS_REQUEST = 'GET_PACK_MEALS_REQUEST',
  GET_PACK_MEALS_SUCCESS = 'GET_PACK_MEALS_SUCCESS',
  GET_PACK_MEALS_FAILED = 'GET_PACK_MEALS_FAILED',

  GET_PACK_MEAL = 'GET_PACK_MEAL',
  GET_PACK_MEAL_REQUEST = 'GET_PACK_MEAL_REQUEST',
  GET_PACK_MEAL_SUCCESS = 'GET_PACK_MEAL_SUCCESS',
  GET_PACK_MEAL_FAILED = 'GET_PACK_MEAL_FAILED',

  BUY_PACK_MEAL = 'BUY_PACK_MEAL',
  BUY_PACK_MEAL_REQUEST = 'BUY_PACK_MEAL_REQUEST',
  BUY_PACK_MEAL_SUCCESS = 'BUY_PACK_MEAL_SUCCESS',
  BUY_PACK_MEAL_FAILED = 'BUY_PACK_MEAL_FAILED',
}
