export enum EIconName {
  Phone = 'Phone',
  Lock = 'Lock',
  Users = 'Users',
  Camera = 'Camera',
  Calendar = 'Calendar',
  AngleRight = 'AngleRight',
  Picture = 'Picture',
  Search = 'Search',
  Cart = 'Cart',
  Bars = 'Bars',
  UserSquare = 'UserSquare',
  Edit = 'Edit',
  Facebook = 'Facebook',
  Instagram = 'Instagram',
  Wheel = 'Wheel',
  Info = 'Info',
  Close = 'Close',
  Medal = 'Medal',
  Gift = 'Gift',
  CreditCard = 'CreditCard',
  Gym = 'Gym',
  Heart = 'Heart',
  History = 'History',
  User = 'User',
  Duplicate = 'Duplicate',
  Plus = 'Plus',
  Quote = 'Quote',
  MapMarker = 'MapMarker',
  Mail = 'Mail',
  LoadingSpin = 'LoadingSpin',
  Logout = 'Logout',
}

export enum EIconColor {
  BLACK = '#000',
  WHITE = '#fff',
  BOULDER = '#777',
  SCARPA_FLOW = '#535256',
  ELECTRIC_VIOLET = '#6338FA',
  BUDDHA_GOLD = '#d79d00',
  INTERNATIONAL_KLEIN_BLUE = '#021EAE',
}
