export enum EProductControllerAction {
  GET_PRODUCTS_FAVORITE = 'GET_PRODUCTS_FAVORITE',
  GET_PRODUCTS_FAVORITE_REQUEST = 'GET_PRODUCTS_FAVORITE_REQUEST',
  GET_PRODUCTS_FAVORITE_SUCCESS = 'GET_PRODUCTS_FAVORITE_SUCCESS',
  GET_PRODUCTS_FAVORITE_FAILED = 'GET_PRODUCTS_FAVORITE_FAILED',

  GET_PRODUCTS = 'GET_PRODUCTS',
  GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST',
  GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS',
  GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED',

  GET_PRODUCTS_SPECIAL = 'GET_PRODUCTS_SPECIAL',
  GET_PRODUCTS_SPECIAL_REQUEST = 'GET_PRODUCTS_SPECIAL_REQUEST',
  GET_PRODUCTS_SPECIAL_SUCCESS = 'GET_PRODUCTS_SPECIAL_SUCCESS',
  GET_PRODUCTS_SPECIAL_FAILED = 'GET_PRODUCTS_SPECIAL_FAILED',

  GET_PRODUCTS_SEARCH = 'GET_PRODUCTS_SEARCH',
  GET_PRODUCTS_SEARCH_REQUEST = 'GET_PRODUCTS_SEARCH_REQUEST',
  GET_PRODUCTS_SEARCH_SUCCESS = 'GET_PRODUCTS_SEARCH_SUCCESS',
  GET_PRODUCTS_SEARCH_FAILED = 'GET_PRODUCTS_SEARCH_FAILED',

  GET_PRODUCT = 'GET_PRODUCT',
  GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST',
  GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS',
  GET_PRODUCT_FAILED = 'GET_PRODUCT_FAILED',

  LIKE_PRODUCT = 'LIKE_PRODUCT',
  LIKE_PRODUCT_REQUEST = 'LIKE_PRODUCT_REQUEST',
  LIKE_PRODUCT_SUCCESS = 'LIKE_PRODUCT_SUCCESS',
  LIKE_PRODUCT_FAILED = 'LIKE_PRODUCT_FAILED',

  UNLIKE_PRODUCT = 'UNLIKE_PRODUCT',
  UNLIKE_PRODUCT_REQUEST = 'UNLIKE_PRODUCT_REQUEST',
  UNLIKE_PRODUCT_SUCCESS = 'UNLIKE_PRODUCT_SUCCESS',
  UNLIKE_PRODUCT_FAILED = 'UNLIKE_PRODUCT_FAILED',

  IS_FAVORITE_PRODUCT = 'IS_FAVORITE_PRODUCT',
  IS_FAVORITE_PRODUCT_REQUEST = 'IS_FAVORITE_PRODUCT_REQUEST',
  IS_FAVORITE_PRODUCT_SUCCESS = 'IS_FAVORITE_PRODUCT_SUCCESS',
  IS_FAVORITE_PRODUCT_FAILED = 'IS_FAVORITE_PRODUCT_FAILED',
}
