export enum EProductControllerAction {
  GET_PRODUCTS_FAVORITE = 'GET_PRODUCTS_FAVORITE',
  GET_PRODUCTS_FAVORITE_REQUEST = 'GET_PRODUCTS_FAVORITE_REQUEST',
  GET_PRODUCTS_FAVORITE_SUCCESS = 'GET_PRODUCTS_FAVORITE_SUCCESS',
  GET_PRODUCTS_FAVORITE_FAILED = 'GET_PRODUCTS_FAVORITE_FAILED',
}
