export enum EProductControllerAction {
  GET_PRODUCTS_FAVORITE = 'GET_PRODUCTS_FAVORITE',
  GET_PRODUCTS_FAVORITE_REQUEST = 'GET_PRODUCTS_FAVORITE_REQUEST',
  GET_PRODUCTS_FAVORITE_SUCCESS = 'GET_PRODUCTS_FAVORITE_SUCCESS',
  GET_PRODUCTS_FAVORITE_FAILED = 'GET_PRODUCTS_FAVORITE_FAILED',

  GET_PRODUCTS = 'GET_PRODUCTS',
  GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST',
  GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS',
  GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED',

  GET_PRODUCT = 'GET_PRODUCT',
  GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST',
  GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS',
  GET_PRODUCT_FAILED = 'GET_PRODUCT_FAILED',
}
