export enum ECartControllerAction {
  GET_CART = 'GET_CART',
  GET_CART_REQUEST = 'GET_CART_REQUEST',
  GET_CART_SUCCESS = 'GET_CART_SUCCESS',
  GET_CART_FAILED = 'GET_CART_FAILED',

  ADD_CART = 'ADD_CART',
  ADD_CART_REQUEST = 'ADD_CART_REQUEST',
  ADD_CART_SUCCESS = 'ADD_CART_SUCCESS',
  ADD_CART_FAILED = 'ADD_CART_FAILED',

  PATCH_CART = 'PATCH_CART',
  PATCH_CART_REQUEST = 'PATCH_CART_REQUEST',
  PATCH_CART_SUCCESS = 'PATCH_CART_SUCCESS',
  PATCH_CART_FAILED = 'PATCH_CART_FAILED',

  DELETE_CART = 'DELETE_CART',
  DELETE_CART_REQUEST = 'DELETE_CART_REQUEST',
  DELETE_CART_SUCCESS = 'DELETE_CART_SUCCESS',
  DELETE_CART_FAILED = 'DELETE_CART_FAILED',
}
