export enum EWheelControllerAction {
  GET_WHEELS_USER = 'GET_WHEELS_USER',
  GET_WHEELS_USER_REQUEST = 'GET_WHEELS_USER_REQUEST',
  GET_WHEELS_USER_SUCCESS = 'GET_WHEELS_USER_SUCCESS',
  GET_WHEELS_USER_FAILED = 'GET_WHEELS_USER_FAILED',

  GET_WHEEL = 'GET_WHEEL',
  GET_WHEEL_REQUEST = 'GET_WHEEL_REQUEST',
  GET_WHEEL_SUCCESS = 'GET_WHEEL_SUCCESS',
  GET_WHEEL_FAILED = 'GET_WHEEL_FAILED',
}
