export enum EWheelControllerAction {
  GET_WHEELS_USER = 'GET_WHEELS_USER',
  GET_WHEELS_USER_REQUEST = 'GET_WHEELS_USER_REQUEST',
  GET_WHEELS_USER_SUCCESS = 'GET_WHEELS_USER_SUCCESS',
  GET_WHEELS_USER_FAILED = 'GET_WHEELS_USER_FAILED',

  GET_WHEEL = 'GET_WHEEL',
  GET_WHEEL_REQUEST = 'GET_WHEEL_REQUEST',
  GET_WHEEL_SUCCESS = 'GET_WHEEL_SUCCESS',
  GET_WHEEL_FAILED = 'GET_WHEEL_FAILED',

  GET_HISTORY_WHEEL = 'GET_HISTORY_WHEEL',
  GET_HISTORY_WHEEL_REQUEST = 'GET_HISTORY_WHEEL_REQUEST',
  GET_HISTORY_WHEEL_SUCCESS = 'GET_HISTORY_WHEEL_SUCCESS',
  GET_HISTORY_WHEEL_FAILED = 'GET_HISTORY_WHEEL_FAILED',

  START_WHEEL = 'START_WHEEL',
  START_WHEEL_REQUEST = 'START_WHEEL_REQUEST',
  START_WHEEL_SUCCESS = 'START_WHEEL_SUCCESS',
  START_WHEEL_FAILED = 'START_WHEEL_FAILED',
}
