export enum EHandbookControllerAction {
  GET_HANDBOOKS = 'GET_HANDBOOKS',
  GET_HANDBOOKS_REQUEST = 'GET_HANDBOOKS_REQUEST',
  GET_HANDBOOKS_SUCCESS = 'GET_HANDBOOKS_SUCCESS',
  GET_HANDBOOKS_FAILED = 'GET_HANDBOOKS_FAILED',

  GET_HANDBOOK = 'GET_HANDBOOK',
  GET_HANDBOOK_REQUEST = 'GET_HANDBOOK_REQUEST',
  GET_HANDBOOK_SUCCESS = 'GET_HANDBOOK_SUCCESS',
  GET_HANDBOOK_FAILED = 'GET_HANDBOOK_FAILED',
}
