export enum EOrderControllerAction {
  GET_ORDERS = 'GET_ORDERS',
  GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST',
  GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS',
  GET_ORDERS_FAILED = 'GET_ORDERS_FAILED',

  GET_ORDER = 'GET_ORDER',
  GET_ORDER_REQUEST = 'GET_ORDER_REQUEST',
  GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS',
  GET_ORDER_FAILED = 'GET_ORDER_FAILED',
}
