export enum EOrderControllerAction {
  GET_ORDERS = 'GET_ORDERS',
  GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST',
  GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS',
  GET_ORDERS_FAILED = 'GET_ORDERS_FAILED',

  GET_ORDER = 'GET_ORDER',
  GET_ORDER_REQUEST = 'GET_ORDER_REQUEST',
  GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS',
  GET_ORDER_FAILED = 'GET_ORDER_FAILED',

  CREATE_ORDER = 'CREATE_ORDER',
  CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST',
  CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS',
  CREATE_ORDER_FAILED = 'CREATE_ORDER_FAILED',

  CANCEL_ORDER = 'CANCEL_ORDER',
  CANCEL_ORDER_REQUEST = 'CANCEL_ORDER_REQUEST',
  CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS',
  CANCEL_ORDER_FAILED = 'CANCEL_ORDER_FAILED',
}
