export enum EPackPtOnlineControllerAction {
  GET_PACK_PT_ONLINES = 'GET_PACK_PT_ONLINES',
  GET_PACK_PT_ONLINES_REQUEST = 'GET_PACK_PT_ONLINES_REQUEST',
  GET_PACK_PT_ONLINES_SUCCESS = 'GET_PACK_PT_ONLINES_SUCCESS',
  GET_PACK_PT_ONLINES_FAILED = 'GET_PACK_PT_ONLINES_FAILED',

  GET_PACK_PT_ONLINE = 'GET_PACK_PT_ONLINE',
  GET_PACK_PT_ONLINE_REQUEST = 'GET_PACK_PT_ONLINE_REQUEST',
  GET_PACK_PT_ONLINE_SUCCESS = 'GET_PACK_PT_ONLINE_SUCCESS',
  GET_PACK_PT_ONLINE_FAILED = 'GET_PACK_PT_ONLINE_FAILED',
}
