export enum EUserMealScheduleControllerAction {
  GET_USER_MEAL_SCHEDULE = 'GET_USER_MEAL_SCHEDULE',
  GET_USER_MEAL_SCHEDULE_REQUEST = 'GET_USER_MEAL_SCHEDULE_REQUEST',
  GET_USER_MEAL_SCHEDULE_SUCCESS = 'GET_USER_MEAL_SCHEDULE_SUCCESS',
  GET_USER_MEAL_SCHEDULE_FAILED = 'GET_USER_MEAL_SCHEDULE_FAILED',

  GET_USER_MEAL_SCHEDULE_BY_DATE = 'GET_USER_MEAL_SCHEDULE_BY_DATE',
  GET_USER_MEAL_SCHEDULE_BY_DATE_REQUEST = 'GET_USER_MEAL_SCHEDULE_BY_DATE_REQUEST',
  GET_USER_MEAL_SCHEDULE_BY_DATE_SUCCESS = 'GET_USER_MEAL_SCHEDULE_BY_DATE_SUCCESS',
  GET_USER_MEAL_SCHEDULE_BY_DATE_FAILED = 'GET_USER_MEAL_SCHEDULE_BY_DATE_FAILED',

  CREATE_USER_MEAL_SCHEDULE = 'CREATE_USER_MEAL_SCHEDULE',
  CREATE_USER_MEAL_SCHEDULE_REQUEST = 'CREATE_USER_MEAL_SCHEDULE_REQUEST',
  CREATE_USER_MEAL_SCHEDULE_SUCCESS = 'CREATE_USER_MEAL_SCHEDULE_SUCCESS',
  CREATE_USER_MEAL_SCHEDULE_FAILED = 'CREATE_USER_MEAL_SCHEDULE_FAILED',

  CREATE_USER_INFO_BODY = 'CREATE_USER_INFO_BODY',
  CREATE_USER_INFO_BODY_REQUEST = 'CREATE_USER_INFO_BODY_REQUEST',
  CREATE_USER_INFO_BODY_SUCCESS = 'CREATE_USER_INFO_BODY_SUCCESS',
  CREATE_USER_INFO_BODY_FAILED = 'CREATE_USER_INFO_BODY_FAILED',
}
