export enum ERankControllerAction {
  GET_HISTORY_POINTS = 'GET_HISTORY_POINTS',
  GET_HISTORY_POINTS_REQUEST = 'GET_HISTORY_POINTS_REQUEST',
  GET_HISTORY_POINTS_SUCCESS = 'GET_HISTORY_POINTS_SUCCESS',
  GET_HISTORY_POINTS_FAILED = 'GET_HISTORY_POINTS_FAILED',

  GET_BONUS = 'GET_BONUS',
  GET_BONUS_REQUEST = 'GET_BONUS_REQUEST',
  GET_BONUS_SUCCESS = 'GET_BONUS_SUCCESS',
  GET_BONUS_FAILED = 'GET_BONUS_FAILED',
}
