export enum ETurnWheelControllerAction {
  GET_TURN_WHEEL_USER = 'GET_TURN_WHEEL_USER',
  GET_TURN_WHEEL_USER_REQUEST = 'GET_TURN_WHEEL_USER_REQUEST',
  GET_TURN_WHEEL_USER_SUCCESS = 'GET_TURN_WHEEL_USER_SUCCESS',
  GET_TURN_WHEEL_USER_FAILED = 'GET_TURN_WHEEL_USER_FAILED',

  BUY_TURN_WHEEL = 'BUY_TURN_WHEEL',
  BUY_TURN_WHEEL_REQUEST = 'BUY_TURN_WHEEL_REQUEST',
  BUY_TURN_WHEEL_SUCCESS = 'BUY_TURN_WHEEL_SUCCESS',
  BUY_TURN_WHEEL_FAILED = 'BUY_TURN_WHEEL_FAILED',

  SHARE_SOCIAL_TURN_WHEEL = 'SHARE_SOCIAL_TURN_WHEEL',
  SHARE_SOCIAL_TURN_WHEEL_REQUEST = 'SHARE_SOCIAL_TURN_WHEEL_REQUEST',
  SHARE_SOCIAL_TURN_WHEEL_SUCCESS = 'SHARE_SOCIAL_TURN_WHEEL_SUCCESS',
  SHARE_SOCIAL_TURN_WHEEL_FAILED = 'SHARE_SOCIAL_TURN_WHEEL_FAILED',
}
