export enum EPackExerciseControllerAction {
  GET_PACK_EXERCISES = 'GET_PACK_EXERCISES',
  GET_PACK_EXERCISES_REQUEST = 'GET_PACK_EXERCISES_REQUEST',
  GET_PACK_EXERCISES_SUCCESS = 'GET_PACK_EXERCISES_SUCCESS',
  GET_PACK_EXERCISES_FAILED = 'GET_PACK_EXERCISES_FAILED',

  GET_PACK_EXERCISE = 'GET_PACK_EXERCISE',
  GET_PACK_EXERCISE_REQUEST = 'GET_PACK_EXERCISE_REQUEST',
  GET_PACK_EXERCISE_SUCCESS = 'GET_PACK_EXERCISE_SUCCESS',
  GET_PACK_EXERCISE_FAILED = 'GET_PACK_EXERCISE_FAILED',

  GET_PACK_EXERCISES_BOUGHT = 'GET_PACK_EXERCISES_BOUGHT',
  GET_PACK_EXERCISES_BOUGHT_REQUEST = 'GET_PACK_EXERCISES_BOUGHT_REQUEST',
  GET_PACK_EXERCISES_BOUGHT_SUCCESS = 'GET_PACK_EXERCISES_BOUGHT_SUCCESS',
  GET_PACK_EXERCISES_BOUGHT_FAILED = 'GET_PACK_EXERCISES_BOUGHT_FAILED',
}
