export enum EMealScheduleStepKey {
  REGISTER = 'REGISTER',

  BODY_INFORMATION = 'BODY_INFORMATION',

  MEAL_PACKAGE = 'MEAL_PACKAGE',
  MEAL_PACKAGE_DETAIL = 'MEAL_PACKAGE_DETAIL',

  BODY_STATUS = 'BODY_STATUS',

  MEAL_SCHEDULE_OVERVIEW = 'MEAL_SCHEDULE_OVERVIEW',
}
